let receptes = [
    {
      "dateModified": "2016-11-04 09:17:09",
      "idDrink": "11000",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Cocktail",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Mojito",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/3z6xdi1589574603.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Highball glass",
      "strIBA": "Contemporary Classics",
      "strIngredient1": "Light rum",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Lime",
      "strIngredient3": "Sugar",
      "strIngredient4": "Mint",
      "strIngredient5": "Soda water",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.",
      "strInstructionsDE": "Minzblätter mit Zucker und Limettensaft verrühren. Füge einen Spritzer Sodawasser hinzu und fülle das Glas mit gebrochenem Eis. Den Rum eingießen und mit Sodawasser übergießen. Garnieren und mit einem Strohhalm servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "2-3 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "Juice of 1 ",
      "strMeasure3": "2 tsp ",
      "strMeasure4": "2-4 ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,ContemporaryClassic,Alcoholic,USA",
      "strVideo": null
    },
    {
      "dateModified": "2016-11-04 09:46:42",
      "idDrink": "11001",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Cocktail",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Old Fashioned",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Old-fashioned glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Bourbon",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Angostura bitters",
      "strIngredient3": "Sugar",
      "strIngredient4": "Water",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.",
      "strInstructionsDE": "Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser hinzufügen. Vermischen, bis sie sich auflösen.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "4.5 cL",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "2 dashes",
      "strMeasure3": "1 cube",
      "strMeasure4": "dash",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic,Alcoholic,Expensive",
      "strVideo": "https://www.youtube.com/watch?v=YsE_igrPXZs"
    },
    {
      "dateModified": "2015-08-18 14:54:32",
      "idDrink": "11002",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Long Island Tea",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tppn6i1589574695.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Highball glass",
      "strIBA": null,
      "strIngredient1": "Vodka",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Light rum",
      "strIngredient3": "Gin",
      "strIngredient4": "Tequila",
      "strIngredient5": "Lemon",
      "strIngredient6": "Coca-Cola",
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.",
      "strInstructionsDE": "Alle Zutaten (außer Cola) mischen und in einem Highball-Glas über Eis gießen. Füge einen Spritzer Cola hinzu, um Farbe zu erhalten. Mit einer Scheibe Zitrone dekorieren und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1/2 oz ",
      "strMeasure3": "1/2 oz ",
      "strMeasure4": "1/2 oz ",
      "strMeasure5": "Juice of 1/2 ",
      "strMeasure6": "1 splash ",
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "Strong,Asia,StrongFlavor,Brunch,Vegetarian",
      "strVideo": null
    },
    {
      "dateModified": "2015-08-18 15:12:07",
      "idDrink": "11003",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Negroni",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Old-fashioned glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Gin",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Campari",
      "strIngredient3": "Sweet Vermouth",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Stir into glass over ice, garnish and serve.",
      "strInstructionsDE": "In ein Glas über das Eis gießen, garnieren und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic",
      "strVideo": "https://www.youtube.com/watch?v=Y4LH0FQlU8Q"
    },
    {
      "dateModified": "2017-09-02 12:45:25",
      "idDrink": "11004",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Whiskey Sour",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Old-fashioned glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Blended whiskey",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Lemon",
      "strIngredient3": "Powdered sugar",
      "strIngredient4": "Cherry",
      "strIngredient5": "Lemon",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
      "strInstructionsDE": "Mit Eis schütteln. In ein gekühltes Glas abseihen, garnieren und servieren. Wenn Sie \"On the rocks\" servieren, die Zutaten in ein old-fashioned, mit Eis gefülltes Glas geben.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "Juice of 1/2 ",
      "strMeasure3": "1/2 tsp ",
      "strMeasure4": "1 ",
      "strMeasure5": "1/2 slice ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic,Alcoholic",
      "strVideo": "https://www.youtube.com/watch?v=hFKZPzfngcU"
    },
    {
      "dateModified": "2017-09-02 12:51:35",
      "idDrink": "11005",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Cocktail",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Dry Martini",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Gin",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Dry Vermouth",
      "strIngredient3": "Olive",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
      "strInstructionsDE": null,
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 2/3 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1/3 oz ",
      "strMeasure3": "1 ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic",
      "strVideo": null
    },
    {
      "dateModified": "2015-08-18 15:06:37",
      "idDrink": "11006",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Daiquiri",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Light rum",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Lime",
      "strIngredient3": "Powdered sugar",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.",
      "strInstructionsDE": "Alle Zutaten in den Shaker mit Eiswürfel geben. Gut schütteln. In einem gekühlten Cocktailglas abseihen.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "Juice of 1/2 ",
      "strMeasure3": "1 tsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic,Beach",
      "strVideo": null
    },
    {
      "dateModified": "2015-08-18 14:42:59",
      "idDrink": "11007",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Margarita",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": "Contemporary Classics",
      "strIngredient1": "Tequila",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Triple sec",
      "strIngredient3": "Lime juice",
      "strIngredient4": "Salt",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
      "strInstructionsDE": "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1/2 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null
    },
    {
      "dateModified": "2017-09-02 12:07:09",
      "idDrink": "11008",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Cocktail",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Manhattan",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hz7p4t1589575281.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Sweet Vermouth",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Bourbon",
      "strIngredient3": "Angostura bitters",
      "strIngredient4": "Ice",
      "strIngredient5": "Maraschino cherry",
      "strIngredient6": "Orange peel",
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Stirred over ice, strained into a chilled glass, garnished, and served up.",
      "strInstructionsDE": "Über Eis gerührt, in ein gekühltes Glas geseiht, garniert und serviert.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "3/4 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "2 1/2 oz Blended ",
      "strMeasure3": "dash ",
      "strMeasure4": "2 or 3 ",
      "strMeasure5": "1 ",
      "strMeasure6": "1 twist of ",
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic",
      "strVideo": "https://www.youtube.com/watch?v=TFWPtkNoF4Y"
    },
    {
      "dateModified": "2017-09-02 17:49:48",
      "idDrink": "11009",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Punch / Party Drink",
      "strCreativeCommonsConfirmed": "Yes",
      "strDrink": "Moscow Mule",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Copper Mug",
      "strIBA": "Contemporary Classics",
      "strIngredient1": "Vodka",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Lime juice",
      "strIngredient3": "Ginger ale",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.",
      "strInstructionsDE": "Mischen Sie Wodka und Ingwerbier in einem mit Eis gefüllten Highball-Glas. Limettensaft hinzufügen. Vorsichtig umrühren. Garnieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "2 oz ",
      "strMeasure3": "8 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:06:18",
      "idDrink": "11010",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "After Dinner Cocktail",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vtytxq1483387578.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Apricot brandy",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Triple sec",
      "strIngredient3": "Lime",
      "strIngredient4": "Lime",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake all ingredients (except lime wedge) with ice and strain into a cocktail glass. Add the wedge of lime and serve.",
      "strInstructionsDE": "Alle Zutaten (außer Limettenkeil) mit Eis schütteln und in ein Cocktailglas abseihen. Den Limettenkeil dazugeben und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "Juice of 1 ",
      "strMeasure4": "1 ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "DinnerParty",
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:06:50",
      "idDrink": "11011",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "After Supper Cocktail",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/quyxwu1483387610.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Triple sec",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Apricot brandy",
      "strIngredient3": "Lemon juice",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 tsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:07:27",
      "idDrink": "11012",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Alabama Slammer",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qtwxwr1483387647.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Highball glass",
      "strIBA": null,
      "strIngredient1": "Southern Comfort",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Amaretto",
      "strIngredient3": "Sloe gin",
      "strIngredient4": "Lemon juice",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Pour all ingredients (except for lemon juice) over ice in a highball glass. Stir, add a dash of lemon juice, and serve.",
      "strInstructionsDE": "Alle Zutaten (außer Zitronensaft) in einem Highball-Glas über Eis gießen. Umrühren, einen Schuss Zitronensaft hinzufügen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 oz ",
      "strMeasure4": "1 dash ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:08:40",
      "idDrink": "11013",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Alaska Cocktail",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wsyryt1483387720.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Orange bitters",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Gin",
      "strIngredient3": "Yellow Chartreuse",
      "strIngredient4": "Lemon peel",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Stir all ingredients with ice, strain contents into a cocktail glass. Drop in a twist of lemon and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis verrühren, Inhalt in ein Cocktailglas abseihen. Einen Spritzer Zitrone dazugeben und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "2 dashes ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 1/2 oz ",
      "strMeasure3": "3/4 oz ",
      "strMeasure4": "Twist of ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2016-11-04 09:50:39",
      "idDrink": "11014",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Alexander",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/urystu1478253039.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": "Unforgettables",
      "strIngredient1": "Gin",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Creme de Cacao",
      "strIngredient3": "Light cream",
      "strIngredient4": "Nutmeg",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis schütteln und in ein Cocktailglas abseihen. Muskatnuss darüber streuen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1/2 oz white ",
      "strMeasure3": "2 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "IBA,Classic,Dairy",
      "strVideo": "https://www.youtube.com/watch?v=qEhRK_v2w2g"
    },
    {
      "dateModified": "2017-01-02 20:09:06",
      "idDrink": "11016",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Brandy Alexander",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tvqxvr1483387746.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Brandy",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Creme de Cacao",
      "strIngredient3": "Light cream",
      "strIngredient4": "Nutmeg",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake all ingredients (except nutmeg) with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
      "strInstructionsDE": "Alle Zutaten (außer Muskatnuss) mit Eis schütteln und in ein Cocktailglas abseihen. Muskatnuss darüber streuen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz white ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:10:29",
      "idDrink": "11019",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Alfie Cocktail",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ypxsqy1483387829.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Lemon vodka",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Triple sec",
      "strIngredient3": "Pineapple juice",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Combine and shake all ingredients with ice, strain into a cocktail glass, and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis mischen und schütteln, in ein Cocktailglas abseihen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 dash ",
      "strMeasure3": "1 tblsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": "Alcoholic",
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:11:13",
      "idDrink": "11020",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Algonquin",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uwryxx1483387873.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Blended whiskey",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Dry Vermouth",
      "strIngredient3": "Pineapple juice",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Combine and shake all ingredients with ice, strain contents into a cocktail glass, and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis mischen und schütteln, Inhalt in ein Cocktailglas abseihen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:12:14",
      "idDrink": "11021",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Allegheny",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uwvyts1483387934.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Dry Vermouth",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Bourbon",
      "strIngredient3": "Blackberry brandy",
      "strIngredient4": "Lemon juice",
      "strIngredient5": "Lemon peel",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Shake all ingredients (except lemon peel) with ice and strain into a cocktail glass. Top with the twist of lemon peel and serve.",
      "strInstructionsDE": "Alle Zutaten (außer Zitronenschale) mit Eis schütteln und in ein Cocktailglas abseihen. Mit der Drehung der Zitronenschale garnieren und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 1/2 tsp ",
      "strMeasure4": "1 1/2 tsp ",
      "strMeasure5": "1 twist of ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    },
    {
      "dateModified": "2017-01-02 20:15:04",
      "idDrink": "11022",
      "strAlcoholic": "Alcoholic",
      "strCategory": "Ordinary Drink",
      "strCreativeCommonsConfirmed": "No",
      "strDrink": "Allies Cocktail",
      "strDrinkAlternate": null,
      "strDrinkDE": null,
      "strDrinkES": null,
      "strDrinkFR": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qvprvp1483388104.jpg",
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strGlass": "Cocktail glass",
      "strIBA": null,
      "strIngredient1": "Dry Vermouth",
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient2": "Gin",
      "strIngredient3": "Kummel",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strInstructions": "Stir all ingredients with ice, strain contents into a cocktail glass, and serve.",
      "strInstructionsDE": "Alle Zutaten mit Eis verrühren, Inhalt in ein Cocktailglas abseihen und servieren.",
      "strInstructionsES": null,
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strMeasure1": "1 oz ",
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 tsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strTags": null,
      "strVideo": null
    }
  ]

export default ({ app }, inject) => {
  // Inject $hello(msg) in Vue, context and store
  inject('receptes',  receptes)
}
